/**
 * Comprehensive Delhi NCR Geospatial Directory for Menu Maps (menumaps.online)
 * Covers all 11 Delhi Districts, 60+ Iconic Dining Neighborhoods,
 * Delhi Metro lines, and key food specialties.
 */

export interface DelhiLocation {
  id: string;
  name: string;
  shortName: string;
  zone: string;
  zoneKey: 'all' | 'north' | 'south' | 'central' | 'west' | 'northwest' | 'southwest' | 'east' | 'ncr';
  latitude: number;
  longitude: number;
  metroStation: string;
  metroLines: string[];
  famousSpecialties: string[];
  tagline: string;
  avgCostForTwo: number;
  isPopularHub: boolean;
  pincode?: string;
  landmarks?: string[];
}

export interface DelhiZoneInfo {
  key: DelhiLocation['zoneKey'];
  label: string;
  icon: string;
  description: string;
}

export const DELHI_ZONES: DelhiZoneInfo[] = [
  { key: 'all', label: 'All Delhi NCR', icon: '🗺️', description: 'Complete 60+ neighborhood directory' },
  { key: 'north', label: 'North & DU', icon: '🎓', description: 'Student addas, shakes & waffles' },
  { key: 'south', label: 'South Delhi', icon: '🍸', description: 'Designer cafes, rooftops & European dining' },
  { key: 'central', label: 'Central & Heritage', icon: '🏛️', description: 'Colonial cafes, Old Delhi & dhabas' },
  { key: 'west', label: 'West Delhi', icon: '🍗', description: 'Tandoori chaap, family feasts & restrobars' },
  { key: 'northwest', label: 'North-West & NSP', icon: '🏢', description: 'NSP towers, Pitampura & Rohini food streets' },
  { key: 'southwest', label: 'South-West & Dwarka', icon: '✈️', description: 'Dwarka sub-city, Aerocity & Vasant Kunj' },
  { key: 'east', label: 'East & Trans-Yamuna', icon: '🥟', description: 'Laxmi Nagar, Mayur Vihar & Vikas Marg' },
  { key: 'ncr', label: 'NCR Gateways', icon: '🏙️', description: 'Noida Sec 18, CyberHub & Indirapuram' },
];

export const DELHI_LOCATIONS: DelhiLocation[] = [
  // =========================================================================
  // 1. NORTH DELHI & DU CAMPUS
  // =========================================================================
  {
    id: 'hudson-lane',
    name: 'Hudson Lane (North Campus)',
    shortName: 'Hudson Lane',
    zone: 'North Delhi',
    zoneKey: 'north',
    latitude: 28.6942,
    longitude: 77.2045,
    metroStation: 'GTB Nagar (Exit Gate 3)',
    metroLines: ['Yellow Line'],
    famousSpecialties: ['Monster Shakes', 'Kurkure Momos', 'Peri Peri Fries', 'Pink Sauce Pasta'],
    tagline: 'The iconic DU student adda packed with themed multi-level cafes',
    avgCostForTwo: 450,
    isPopularHub: true,
    pincode: '110009',
    landmarks: ['Near GTB Nagar Metro', 'Behind Kingsway Camp'],
  },
  {
    id: 'kamla-nagar',
    name: 'Kamla Nagar (Bungalow Road)',
    shortName: 'Kamla Nagar',
    zone: 'North Delhi',
    zoneKey: 'north',
    latitude: 28.6808,
    longitude: 77.2032,
    metroStation: 'Vishwavidyalaya (Exit Gate 2)',
    metroLines: ['Yellow Line'],
    famousSpecialties: ['Chache Di Hatti Chole Bhature', 'Waffles', 'Cold Coffee', 'Kathi Rolls'],
    tagline: 'Vibrant college shopping market with legendary breakfast joints',
    avgCostForTwo: 350,
    isPopularHub: true,
    pincode: '110007',
    landmarks: ['Spark Mall', 'Bungalow Road', 'Hansraj College Road'],
  },
  {
    id: 'majnu-ka-tilla',
    name: 'Majnu Ka Tila (Little Tibet)',
    shortName: 'MKT',
    zone: 'North Delhi',
    zoneKey: 'north',
    latitude: 28.7011,
    longitude: 77.2294,
    metroStation: 'Vidhan Sabha (Exit Gate 2)',
    metroLines: ['Yellow Line'],
    famousSpecialties: ['Laphing', 'Thukpa', 'Kothey Momos', 'Korean Corn Dogs', 'Butter Tea'],
    tagline: 'Riverside Himalayan colony with prayer flags & bohemian rooftops',
    avgCostForTwo: 550,
    isPopularHub: true,
    pincode: '110054',
    landmarks: ['Signature Bridge', 'MKT Monastery', 'Aruna Nagar'],
  },
  {
    id: 'mukherjee-nagar',
    name: 'Mukherjee Nagar (Batra Complex)',
    shortName: 'Mukherjee Nagar',
    zone: 'North Delhi',
    zoneKey: 'north',
    latitude: 28.7089,
    longitude: 77.2144,
    metroStation: 'GTB Nagar (Exit Gate 2)',
    metroLines: ['Yellow Line'],
    famousSpecialties: ['Unlimited Student Thalis', 'Kulhad Chai', 'Soya Malai Chaap', 'Momos'],
    tagline: 'High-octane aspirant hub with late-night food addas & budget messes',
    avgCostForTwo: 300,
    isPopularHub: true,
    pincode: '110009',
    landmarks: ['Batra Cinema Complex', 'Banda Bahadur Marg'],
  },
  {
    id: 'model-town',
    name: 'Model Town (Phase 2 & 3)',
    shortName: 'Model Town',
    zone: 'North Delhi',
    zoneKey: 'north',
    latitude: 28.7033,
    longitude: 77.1932,
    metroStation: 'Model Town Metro',
    metroLines: ['Yellow Line'],
    famousSpecialties: ['Artisan Bakery Desserts', 'Afghani Chaap', 'Cold Brews', 'Gourmet Pizzas'],
    tagline: 'Upscale residential dining hubs, terrace cafes & family dessert parlors',
    avgCostForTwo: 600,
    isPopularHub: false,
    pincode: '110009',
    landmarks: ['Naini Lake', 'Model Town 2 Market'],
  },
  {
    id: 'civil-lines',
    name: 'Civil Lines (Heritage Greenery)',
    shortName: 'Civil Lines',
    zone: 'North Delhi',
    zoneKey: 'north',
    latitude: 28.6811,
    longitude: 77.2227,
    metroStation: 'Civil Lines Metro',
    metroLines: ['Yellow Line'],
    famousSpecialties: ['High Tea', 'Club Sandwiches', 'Mughlai Gravies', 'Artisan Coffee'],
    tagline: 'Tree-lined colonial avenues with quiet luxury garden cafes',
    avgCostForTwo: 800,
    isPopularHub: false,
    pincode: '110054',
    landmarks: ['Delhi Ridge', 'Oberoi Maidens'],
  },
  {
    id: 'vijay-nagar',
    name: 'Vijay Nagar & Single Storey',
    shortName: 'Vijay Nagar',
    zone: 'North Delhi',
    zoneKey: 'north',
    latitude: 28.6975,
    longitude: 77.2025,
    metroStation: 'GTB Nagar',
    metroLines: ['Yellow Line'],
    famousSpecialties: ['South Indian Platters', 'Late Night Burgers', 'Momos', 'Tea Points'],
    tagline: 'Quiet DU residential lanes full of student snack dens & breakfast stalls',
    avgCostForTwo: 280,
    isPopularHub: false,
    pincode: '110009',
  },

  // =========================================================================
  // 2. SOUTH DELHI HUBS
  // =========================================================================
  {
    id: 'hauz-khas-village',
    name: 'Hauz Khas Village & Deer Park',
    shortName: 'Hauz Khas Village',
    zone: 'South Delhi',
    zoneKey: 'south',
    latitude: 28.5494,
    longitude: 77.1932,
    metroStation: 'IIT Delhi / Hauz Khas',
    metroLines: ['Yellow Line', 'Magenta Line'],
    famousSpecialties: ['Lake-view Sunset Coffee', 'Wood-fired Pizza', 'Mezze Platters', 'Cocktails'],
    tagline: '14th-century medieval lake views, graffiti corridors & chic bistros',
    avgCostForTwo: 850,
    isPopularHub: true,
    pincode: '110016',
    landmarks: ['Hauz Khas Fort', 'Deer Park'],
  },
  {
    id: 'satya-niketan',
    name: 'Satya Niketan (South Campus)',
    shortName: 'Satya Niketan',
    zone: 'South Delhi',
    zoneKey: 'south',
    latitude: 28.5882,
    longitude: 77.1654,
    metroStation: 'Durgabai Deshmukh South Campus (Gate 2)',
    metroLines: ['Pink Line'],
    famousSpecialties: ['Ferrero Shakes', 'Tandoori Momos', 'Ghee Roast Dosa', 'Four-Cheese Pizzas'],
    tagline: 'South DU student haven: pocket-friendly rooftop cafes & fast-food addas',
    avgCostForTwo: 420,
    isPopularHub: true,
    pincode: '110021',
    landmarks: ['Opposite Sri Venkateswara College', 'Benito Juarez Marg'],
  },
  {
    id: 'saket-champa-gali',
    name: 'Saket & Champa Gali (Saidulajab)',
    shortName: 'Saket / Champa Gali',
    zone: 'South Delhi',
    zoneKey: 'south',
    latitude: 28.5186,
    longitude: 77.1996,
    metroStation: 'Saket (Exit Gate 2)',
    metroLines: ['Yellow Line'],
    famousSpecialties: ['Artisan Roasteries', 'Sourdough Bakes', 'Vietnamese Coffee', 'Bagels'],
    tagline: 'Fairy-lit bohemian cobblestone alleyway with indie art cafes',
    avgCostForTwo: 750,
    isPopularHub: true,
    pincode: '110030',
    landmarks: ['Khasra 258 Lane', 'Near Saket PVR Anupam'],
  },
  {
    id: 'malviya-nagar',
    name: 'Malviya Nagar (Main Market)',
    shortName: 'Malviya Nagar',
    zone: 'South Delhi',
    zoneKey: 'south',
    latitude: 28.5298,
    longitude: 77.2078,
    metroStation: 'Malviya Nagar (Exit Gate 3)',
    metroLines: ['Yellow Line'],
    famousSpecialties: ['Amritsari Chur Chur Naan', 'Mysore Masala Dosa', 'Dal Makhani', 'Kesari Jalebi'],
    tagline: 'Bustling South Delhi hub with legendary street dhabas & sweets',
    avgCostForTwo: 450,
    isPopularHub: true,
    pincode: '110017',
    landmarks: ['Corner Market', 'Malviya Nagar Gol Chakkar'],
  },
  {
    id: 'greater-kailash-1',
    name: 'Greater Kailash 1 (M & N Block)',
    shortName: 'GK 1',
    zone: 'South Delhi',
    zoneKey: 'south',
    latitude: 28.5529,
    longitude: 77.2372,
    metroStation: 'Greater Kailash Metro / Kailash Colony',
    metroLines: ['Magenta Line', 'Violet Line'],
    famousSpecialties: ['Artisan Gelato', 'Sushi & Dimsums', 'Specialty Coffee', 'Gourmet Salads'],
    tagline: 'Delhi’s prime lifestyle & fine-casual market for brunch & evening dining',
    avgCostForTwo: 950,
    isPopularHub: true,
    pincode: '110048',
    landmarks: ['M-Block Market GK1', 'N-Block Market'],
  },
  {
    id: 'greater-kailash-2',
    name: 'Greater Kailash 2 (M-Block Market)',
    shortName: 'GK 2',
    zone: 'South Delhi',
    zoneKey: 'south',
    latitude: 28.5355,
    longitude: 77.2425,
    metroStation: 'Greater Kailash Metro',
    metroLines: ['Magenta Line'],
    famousSpecialties: ['Craft Burgers', 'Italian Trattorias', 'Pan-Asian Curries', 'Cheesecakes'],
    tagline: 'Chic restaurant hub with premier European bakeries and rooftop bars',
    avgCostForTwo: 1100,
    isPopularHub: false,
    pincode: '110048',
    landmarks: ['M-Block Market GK2', 'Jahanpanah City Forest Edge'],
  },
  {
    id: 'defence-colony',
    name: 'Defence Colony (Def Col Market)',
    shortName: 'Def Col',
    zone: 'South Delhi',
    zoneKey: 'south',
    latitude: 28.5742,
    longitude: 77.2317,
    metroStation: 'Lajpat Nagar / Moolchand',
    metroLines: ['Pink Line', 'Violet Line'],
    famousSpecialties: ['Kathis & Rolls', 'Middle Eastern Mezze', 'Artisan Bakery', 'Steaks'],
    tagline: 'Posh South Delhi enclave renowned for century-old bakeries & restrobars',
    avgCostForTwo: 900,
    isPopularHub: false,
    pincode: '110024',
    landmarks: ['Def Col Flyover', 'Defence Colony Main Market'],
  },
  {
    id: 'green-park',
    name: 'Green Park & Hauz Khas Enclave',
    shortName: 'Green Park',
    zone: 'South Delhi',
    zoneKey: 'south',
    latitude: 28.5588,
    longitude: 77.2028,
    metroStation: 'Green Park Metro',
    metroLines: ['Yellow Line'],
    famousSpecialties: ['Nagaland Thalis', 'Korean Bibimbap', 'Classic South Indian', 'Biryani'],
    tagline: 'Eclectic neighborhood market with pan-Asian & authentic regional dining',
    avgCostForTwo: 650,
    isPopularHub: false,
    pincode: '110016',
    landmarks: ['Green Park Main Market', 'Uphar Cinema Complex'],
  },
  {
    id: 'cr-park',
    name: 'CR Park (Chittaranjan Park)',
    shortName: 'CR Park',
    zone: 'South Delhi',
    zoneKey: 'south',
    latitude: 28.5398,
    longitude: 77.2512,
    metroStation: 'Nehru Enclave / Greater Kailash',
    metroLines: ['Magenta Line'],
    famousSpecialties: ['Fish Fry & Cutlet', 'Kolkata Kathi Rolls', 'Mishti Doi & Rasgulla', 'Mughlai Biryani'],
    tagline: 'Little Kolkata: the holy grail of authentic Bengali street eats & sweets',
    avgCostForTwo: 400,
    isPopularHub: true,
    pincode: '110019',
    landmarks: ['Market 1', 'Market 2', 'Bipin Chandra Pal Kendra'],
  },
  {
    id: 'nehru-place-epicuria',
    name: 'Nehru Place & Epicuria Food Mall',
    shortName: 'Epicuria / Nehru Place',
    zone: 'South Delhi',
    zoneKey: 'south',
    latitude: 28.5492,
    longitude: 77.2525,
    metroStation: 'Nehru Place (Direct Station Concourse)',
    metroLines: ['Violet Line'],
    famousSpecialties: ['Craft Beer', 'Neapolitan Pizza', 'Japanese Ramen', 'Gourmet Sliders'],
    tagline: 'Underground transit food mall connecting top international cafe chains',
    avgCostForTwo: 900,
    isPopularHub: false,
    pincode: '110019',
    landmarks: ['Epicuria Under Metro', 'Nehru Place Tech Hub'],
  },

  // =========================================================================
  // 3. CENTRAL DELHI & HERITAGE
  // =========================================================================
  {
    id: 'connaught-place',
    name: 'Connaught Place (CP Heritage)',
    shortName: 'Connaught Place (CP)',
    zone: 'Central Delhi',
    zoneKey: 'central',
    latitude: 28.6304,
    longitude: 77.2177,
    metroStation: 'Rajiv Chowk (Interchange Exit Gate 7/8)',
    metroLines: ['Yellow Line', 'Blue Line'],
    famousSpecialties: ['Wenger’s Patties', 'Keventers Thick Shakes', 'Colonial Coffee', 'Rooftop Pizzas'],
    tagline: 'Iconic Georgian colonnades, heritage bakeries & Central Park rooftops',
    avgCostForTwo: 850,
    isPopularHub: true,
    pincode: '110001',
    landmarks: ['Inner Circle', 'Outer Circle', 'Palika Bazaar', 'Janpath'],
  },
  {
    id: 'chandni-chowk',
    name: 'Chandni Chowk & Old Delhi Heritage',
    shortName: 'Chandni Chowk',
    zone: 'Central Delhi',
    zoneKey: 'central',
    latitude: 28.6506,
    longitude: 77.2334,
    metroStation: 'Chandni Chowk (Exit Gate 1)',
    metroLines: ['Yellow Line'],
    famousSpecialties: ['Desi Ghee Jalebi with Rabri', 'Paranthe Wali Gali', 'Natraj Dahi Bhalla', 'Bedmi Poori'],
    tagline: '350-year-old culinary labyrinth of Mughal halwais & heirloom chaat recipes',
    avgCostForTwo: 350,
    isPopularHub: true,
    pincode: '110006',
    landmarks: ['Town Hall Promenade', 'Dariba Kalan', 'Gauri Shankar Temple'],
  },
  {
    id: 'jama-masjid',
    name: 'Jama Masjid & Matia Mahal',
    shortName: 'Jama Masjid',
    zone: 'Central Delhi',
    zoneKey: 'central',
    latitude: 28.6508,
    longitude: 77.2339,
    metroStation: 'Jama Masjid (Exit Gate 2)',
    metroLines: ['Violet Line'],
    famousSpecialties: ['Mutton Nihari', 'Butter Chicken Seekh Kebab', 'Shahi Tukda', 'Khameeri Roti'],
    tagline: 'Legendary Mughlai street feast corridor packed with royal history',
    avgCostForTwo: 450,
    isPopularHub: true,
    pincode: '110006',
    landmarks: ['Jama Masjid Gate 1', 'Matia Mahal Gali'],
  },
  {
    id: 'karol-bagh',
    name: 'Karol Bagh (Ajmal Khan & Pusa Road)',
    shortName: 'Karol Bagh',
    zone: 'Central Delhi',
    zoneKey: 'central',
    latitude: 28.6448,
    longitude: 77.1895,
    metroStation: 'Karol Bagh (Exit Gate 4)',
    metroLines: ['Blue Line'],
    famousSpecialties: ['Roshan Di Kulfi', 'Amritsari Kulcha', 'Methi Chole Bhature', 'South Indian Dosas'],
    tagline: 'Timeless Punjabi shopping district filled with heritage food legends',
    avgCostForTwo: 400,
    isPopularHub: true,
    pincode: '110005',
    landmarks: ['Ajmal Khan Road', 'Arya Samaj Road'],
  },
  {
    id: 'old-rajendra-nagar',
    name: 'Old Rajendra Nagar & Rajendra Place',
    shortName: 'Old Rajendra Nagar',
    zone: 'Central Delhi',
    zoneKey: 'central',
    latitude: 28.6415,
    longitude: 77.1824,
    metroStation: 'Rajendra Place / Karol Bagh',
    metroLines: ['Blue Line'],
    famousSpecialties: ['Gujarati Unlimited Thali', 'Soya Chaap', 'Student Meals', 'Cutting Chai'],
    tagline: 'Bustling civil service aspirant hub with wholesome affordable regional dining',
    avgCostForTwo: 320,
    isPopularHub: false,
    pincode: '110060',
    landmarks: ['Bada Bazar Road', 'Shankar Road'],
  },
  {
    id: 'bengali-market',
    name: 'Bengali Market & Mandi House',
    shortName: 'Bengali Market',
    zone: 'Central Delhi',
    zoneKey: 'central',
    latitude: 28.6292,
    longitude: 77.2341,
    metroStation: 'Mandi House (Exit Gate 1)',
    metroLines: ['Blue Line', 'Violet Line'],
    famousSpecialties: ['Nathus Sweets', 'Bengali Sweet House Chaat', 'Chole Bhature', 'Filter Coffee'],
    tagline: 'Cultural & theatre corridor famous for iconic chaat and traditional sweets',
    avgCostForTwo: 380,
    isPopularHub: false,
    pincode: '110001',
    landmarks: ['Tansen Marg', 'Mandi House Circle'],
  },

  // =========================================================================
  // 4. WEST DELHI DINING CORRIDOR
  // =========================================================================
  {
    id: 'rajouri-garden',
    name: 'Rajouri Garden (Main Market & Ring Road)',
    shortName: 'Rajouri Garden',
    zone: 'West Delhi',
    zoneKey: 'west',
    latitude: 28.6475,
    longitude: 77.1215,
    metroStation: 'Rajouri Garden (Interchange Exit Gate 4/5)',
    metroLines: ['Blue Line', 'Pink Line'],
    famousSpecialties: ['Sizzling Afghani Chaap', 'Butter Chicken Naan Combo', 'Loaded Platters', 'Cocktails'],
    tagline: 'West Delhi’s celebration capital: grand restrobars, restro-lounges & markets',
    avgCostForTwo: 700,
    isPopularHub: true,
    pincode: '110027',
    landmarks: ['Main Market', 'BK Dutt Market', 'City Square Mall'],
  },
  {
    id: 'punjabi-bagh',
    name: 'Punjabi Bagh (Club Road)',
    shortName: 'Punjabi Bagh',
    zone: 'West Delhi',
    zoneKey: 'west',
    latitude: 28.6672,
    longitude: 77.1245,
    metroStation: 'Punjabi Bagh West / Shivaji Park',
    metroLines: ['Pink Line', 'Green Line'],
    famousSpecialties: ['Rooftop Shisha & Mocktails', 'Wood-fired Sourdough', 'Butter Paneer', 'Waffles'],
    tagline: 'Glamorous nightlife & dining avenue lined with multi-floor terrace cafes',
    avgCostForTwo: 850,
    isPopularHub: true,
    pincode: '110026',
    landmarks: ['Club Road', 'Central Market Punjabi Bagh'],
  },
  {
    id: 'paschim-vihar',
    name: 'Paschim Vihar (Jwala Heri & Club Road)',
    shortName: 'Paschim Vihar',
    zone: 'West Delhi',
    zoneKey: 'west',
    latitude: 28.6715,
    longitude: 77.0988,
    metroStation: 'Paschim Vihar West (Green Line)',
    metroLines: ['Green Line'],
    famousSpecialties: ['Tandoori Momos', 'Pav Bhaji', 'Malai Chaap Rolls', 'Thick Cold Shakes'],
    tagline: 'Famous street food paradise anchored by Jwala Heri and lively terrace cafes',
    avgCostForTwo: 450,
    isPopularHub: true,
    pincode: '110063',
    landmarks: ['Jwala Heri Market', 'Bhartendu Harishchandra Marg'],
  },
  {
    id: 'janakpuri',
    name: 'Janakpuri (District Centre & B-Block)',
    shortName: 'Janakpuri',
    zone: 'West Delhi',
    zoneKey: 'west',
    latitude: 28.6292,
    longitude: 77.0818,
    metroStation: 'Janakpuri West (Interchange)',
    metroLines: ['Blue Line', 'Magenta Line'],
    famousSpecialties: ['Craft Burgers', 'Dhabas & Handi Gravies', 'Pizzas', 'Falooda Kulfi'],
    tagline: 'Major transit commercial hub with open-air food courts & cozy student cafes',
    avgCostForTwo: 500,
    isPopularHub: false,
    pincode: '110058',
    landmarks: ['Janakpuri District Centre (JDC)', 'Unity One Mall'],
  },
  {
    id: 'tilak-nagar',
    name: 'Tilak Nagar (Central Market)',
    shortName: 'Tilak Nagar',
    zone: 'West Delhi',
    zoneKey: 'west',
    latitude: 28.6365,
    longitude: 77.0965,
    metroStation: 'Tilak Nagar Metro',
    metroLines: ['Blue Line'],
    famousSpecialties: ['Amritsari Fish Fry', 'Malai Soya Chaap', 'Tandoori Chicken', 'Jalebi'],
    tagline: 'Famous Punjabi food corridor with non-veg & tandoori chaap street stalls',
    avgCostForTwo: 400,
    isPopularHub: false,
    pincode: '110018',
    landmarks: ['Jail Road', 'Central Market Tilak Nagar'],
  },
  {
    id: 'nangloi',
    name: 'Nangloi (Rohtak Road & Metro Corridor)',
    shortName: 'Nangloi',
    zone: 'West Delhi',
    zoneKey: 'west',
    latitude: 28.6752,
    longitude: 77.0588,
    metroStation: 'Nangloi (Green Line, Exit Gate 2)',
    metroLines: ['Green Line'],
    famousSpecialties: ['Dal Bukhara', 'Chur Chur Naan Thalis', 'Malai Soya Chaap', 'Family Platters'],
    tagline: 'Generous desi ghee family restaurants & hidden rooftop hangout cafes',
    avgCostForTwo: 450,
    isPopularHub: true,
    pincode: '110041',
    landmarks: ['Rohtak Road', 'Nangloi Chowk'],
  },

  // =========================================================================
  // 5. NORTH-WEST DELHI & NSP
  // =========================================================================
  {
    id: 'netaji-subhash-place',
    name: 'Netaji Subhash Place (NSP Complex)',
    shortName: 'NSP',
    zone: 'North-West Delhi',
    zoneKey: 'northwest',
    latitude: 28.6948,
    longitude: 77.1492,
    metroStation: 'Netaji Subhash Place (Interchange Red & Pink)',
    metroLines: ['Red Line', 'Pink Line'],
    famousSpecialties: ['Tower Milkshakes', 'Kurkure Momos', 'Chili Potato Bowls', 'Belgian Waffles'],
    tagline: 'One of Delhi’s highest footfall open-air street eats & corporate food hubs',
    avgCostForTwo: 450,
    isPopularHub: true,
    pincode: '110034',
    landmarks: ['Max Tower', 'Ring Road Mall', 'Pearls Omaxe'],
  },
  {
    id: 'pitampura',
    name: 'Pitampura (Kapil Vihar & Rani Bagh)',
    shortName: 'Pitampura',
    zone: 'North-West Delhi',
    zoneKey: 'northwest',
    latitude: 28.6988,
    longitude: 77.1355,
    metroStation: 'Pitampura / Kohat Enclave',
    metroLines: ['Red Line'],
    famousSpecialties: ['Pav Bhaji', 'Golgappas & Chaat', 'Tandoori Soya Chaap', 'Sundae Shakes'],
    tagline: 'Legendary street food lanes with late-night dessert parlors',
    avgCostForTwo: 380,
    isPopularHub: true,
    pincode: '110034',
    landmarks: ['Kapil Vihar Market', 'Kohat Enclave Market'],
  },
  {
    id: 'rohini-sector-7-8-9',
    name: 'Rohini (Sector 7, 8, 9 & D-Mall)',
    shortName: 'Rohini Hub',
    zone: 'North-West Delhi',
    zoneKey: 'northwest',
    latitude: 28.7125,
    longitude: 77.1215,
    metroStation: 'Rohini East / Rohini West',
    metroLines: ['Red Line'],
    famousSpecialties: ['Afghani Malai Momos', 'Cheesy Loaded Burgers', 'Nutella Shakes', 'Tandoori Chaap'],
    tagline: 'Vibrant youth food street lined with trendy quick-service cafes',
    avgCostForTwo: 360,
    isPopularHub: true,
    pincode: '110085',
    landmarks: ['DC Chowk Market Sec 9', 'D-Mall Sec 10'],
  },
  {
    id: 'rohini-sector-13-14',
    name: 'Rohini (Prashant Vihar & Sec 13/14)',
    shortName: 'Prashant Vihar',
    zone: 'North-West Delhi',
    zoneKey: 'northwest',
    latitude: 28.7188,
    longitude: 77.1325,
    metroStation: 'Rohini East',
    metroLines: ['Red Line'],
    famousSpecialties: ['Italian Wood-Fired Pizza', 'Artisan Pastries', 'Rolls', 'Cold Coffee'],
    tagline: 'Cozy neighbourhood dining pockets with aesthetic family cafes',
    avgCostForTwo: 450,
    isPopularHub: false,
    pincode: '110085',
    landmarks: ['Prashant Vihar Market', 'Japanese Park Edge'],
  },
  {
    id: 'shalimar-bagh',
    name: 'Shalimar Bagh (AL Market & Club Road)',
    shortName: 'Shalimar Bagh',
    zone: 'North-West Delhi',
    zoneKey: 'northwest',
    latitude: 28.7145,
    longitude: 77.1645,
    metroStation: 'Shalimar Bagh (Pink Line)',
    metroLines: ['Pink Line'],
    famousSpecialties: ['Tandoori Momos', 'Baked Pasta', 'Specialty Chaap', 'Ice Cream Parlors'],
    tagline: 'Affluent residential market full of boutique bakeries & family dhabas',
    avgCostForTwo: 500,
    isPopularHub: false,
    pincode: '110088',
    landmarks: ['AL Block Market', 'Club Road Shalimar Bagh'],
  },
  {
    id: 'ashok-vihar',
    name: 'Ashok Vihar (Deep Market Phase 1 & 2)',
    shortName: 'Ashok Vihar',
    zone: 'North-West Delhi',
    zoneKey: 'northwest',
    latitude: 28.6945,
    longitude: 77.1788,
    metroStation: 'Kanhaiya Nagar / Keshav Puram',
    metroLines: ['Red Line'],
    famousSpecialties: ['Chaat Bowls', 'Kathi Rolls', 'South Indian Dosas', 'Belgian Chocolate Waffles'],
    tagline: 'Community food hub anchored by the bustling Deep Market shopping square',
    avgCostForTwo: 420,
    isPopularHub: false,
    pincode: '110052',
    landmarks: ['Deep Market Phase 1', 'Major Dhyan Chand Stadium'],
  },

  // =========================================================================
  // 6. SOUTH-WEST DELHI & DWARKA
  // =========================================================================
  {
    id: 'dwarka-sector-6-10',
    name: 'Dwarka (Sector 6 & 10 Markets)',
    shortName: 'Dwarka Central',
    zone: 'South-West Delhi',
    zoneKey: 'southwest',
    latitude: 28.5862,
    longitude: 77.0655,
    metroStation: 'Dwarka Sector 10 (Blue Line)',
    metroLines: ['Blue Line'],
    famousSpecialties: ['Tandoori Chaap', 'Momos', 'Dosa Platters', 'Monster Shakes'],
    tagline: 'Dwarka’s premier neighborhood dining square filled with terrace cafes',
    avgCostForTwo: 480,
    isPopularHub: true,
    pincode: '110075',
    landmarks: ['Sector 6 Central Market', 'Sector 10 DDA Market'],
  },
  {
    id: 'dwarka-sector-12-14',
    name: 'Dwarka (Vegas Mall & Sec 12/14)',
    shortName: 'Dwarka Vegas Strip',
    zone: 'South-West Delhi',
    zoneKey: 'southwest',
    latitude: 28.6015,
    longitude: 77.0325,
    metroStation: 'Dwarka Sector 14 / Sector 12',
    metroLines: ['Blue Line'],
    famousSpecialties: ['Gourmet Burgers', 'Sushi', 'Artisan Coffee', 'Microbrew Dining'],
    tagline: 'Modern retail & dining avenue surrounding Vegas Mall entertainment plaza',
    avgCostForTwo: 750,
    isPopularHub: false,
    pincode: '110078',
    landmarks: ['Vegas Mall', 'NSUT Campus Edge'],
  },
  {
    id: 'aerocity-worldmark',
    name: 'Aerocity (Worldmark Dining Boulevard)',
    shortName: 'Aerocity',
    zone: 'South-West Delhi',
    zoneKey: 'southwest',
    latitude: 28.5502,
    longitude: 77.1215,
    metroStation: 'Delhi Aerocity (Airport Express)',
    metroLines: ['Airport Express Line'],
    famousSpecialties: ['Gourmet Steaks', 'Japanese Robata', 'Craft Beers', 'Artisan Sourdough'],
    tagline: 'Ultra-modern international luxury dining & bar boulevard next to IGI Airport',
    avgCostForTwo: 1400,
    isPopularHub: true,
    pincode: '110037',
    landmarks: ['Worldmark 1, 2, 3', 'The Walk Aerocity'],
  },
  {
    id: 'vasant-kunj',
    name: 'Vasant Kunj (Nelson Mandela Marg)',
    shortName: 'Vasant Kunj',
    zone: 'South-West Delhi',
    zoneKey: 'southwest',
    latitude: 28.5288,
    longitude: 77.1555,
    metroStation: 'Chhatarpur / Vasant Vihar',
    metroLines: ['Yellow Line', 'Magenta Line'],
    famousSpecialties: ['Wood-fired Pizza', 'Pan-Asian Curries', 'Brunch Pancakes', 'Craft Coffee'],
    tagline: 'High-end mall dining & peaceful green farm lounge venues',
    avgCostForTwo: 950,
    isPopularHub: false,
    pincode: '110070',
    landmarks: ['DLF Promenade', 'Ambience Mall VK', 'Sector C Market'],
  },
  {
    id: 'chanakyapuri-malcha-marg',
    name: 'Chanakyapuri (Malcha Marg & Yashwant Place)',
    shortName: 'Chanakyapuri',
    zone: 'South-West Delhi',
    zoneKey: 'southwest',
    latitude: 28.5985,
    longitude: 77.1855,
    metroStation: 'Durgabai Deshmukh South Campus / Lok Kalyan Marg',
    metroLines: ['Pink Line', 'Yellow Line'],
    famousSpecialties: ['Sizzling Yashwant Place Momos', 'Thukpa', 'Euro Bistro Salads', 'Craft Bakery'],
    tagline: 'Diplomatic enclave: legendary steaming momo stalls and elite fine-dining bistros',
    avgCostForTwo: 750,
    isPopularHub: true,
    pincode: '110021',
    landmarks: ['Yashwant Place Market', 'Malcha Marg Community Centre'],
  },

  // =========================================================================
  // 7. EAST DELHI & TRANS-YAMUNA
  // =========================================================================
  {
    id: 'laxmi-nagar',
    name: 'Laxmi Nagar (Vikas Marg & V3S Mall)',
    shortName: 'Laxmi Nagar',
    zone: 'East Delhi',
    zoneKey: 'east',
    latitude: 28.6308,
    longitude: 77.2778,
    metroStation: 'Laxmi Nagar (Blue Line, Gate 1)',
    metroLines: ['Blue Line'],
    famousSpecialties: ['Kurkure Momos', 'Pav Bhaji', 'Kathi Rolls', 'Cold Coffee', 'Desi Chinese Bowls'],
    tagline: 'East Delhi’s ultimate student & budget foodie hub along vibrant Vikas Marg',
    avgCostForTwo: 320,
    isPopularHub: true,
    pincode: '110092',
    landmarks: ['V3S Mall', 'Vikas Marg Food Strip', 'Main Market'],
  },
  {
    id: 'preet-vihar',
    name: 'Preet Vihar (Community Centre)',
    shortName: 'Preet Vihar',
    zone: 'East Delhi',
    zoneKey: 'east',
    latitude: 28.6415,
    longitude: 77.2955,
    metroStation: 'Preet Vihar (Blue Line)',
    metroLines: ['Blue Line'],
    famousSpecialties: ['Handmade Thin Crust Pizza', 'Afghani Soya Chaap', 'Waffles', 'Mocktails'],
    tagline: 'Prime East Delhi commercial hangout with lively cafes & family dessert bars',
    avgCostForTwo: 550,
    isPopularHub: true,
    pincode: '110092',
    landmarks: ['Preet Vihar Commercial Complex', 'G-Block Market'],
  },
  {
    id: 'mayur-vihar-phase-1',
    name: 'Mayur Vihar (Phase 1 & Acharya Niketan)',
    shortName: 'Mayur Vihar 1',
    zone: 'East Delhi',
    zoneKey: 'east',
    latitude: 28.6085,
    longitude: 77.2965,
    metroStation: 'Mayur Vihar Phase 1 (Interchange)',
    metroLines: ['Blue Line', 'Pink Line'],
    famousSpecialties: ['South Indian Dosas', 'Chur Chur Naan', 'Tibetan Momos', 'Sweet Bengali Treats'],
    tagline: 'Dense residential food market with authentic regional south & street flavors',
    avgCostForTwo: 360,
    isPopularHub: true,
    pincode: '110091',
    landmarks: ['Acharya Niketan Market', 'Pocket 1 Shopping Complex'],
  },
  {
    id: 'anand-vihar-karkardooma',
    name: 'Karkardooma & Anand Vihar (Cross River Mall)',
    shortName: 'Karkardooma',
    zone: 'East Delhi',
    zoneKey: 'east',
    latitude: 28.6545,
    longitude: 77.3025,
    metroStation: 'Karkardooma (Blue & Pink Interchange)',
    metroLines: ['Blue Line', 'Pink Line'],
    famousSpecialties: ['Craft Cocktails', 'Dal Makhani & Naan', 'Burgers', 'Coffee Lounges'],
    tagline: 'Multi-level restrobars & shopping plaza cafes near the interstate hub',
    avgCostForTwo: 650,
    isPopularHub: false,
    pincode: '110092',
    landmarks: ['Cross River Mall', 'Karkardooma Court Road'],
  },

  // =========================================================================
  // 8. NCR EXTENSION GATEWAYS
  // =========================================================================
  {
    id: 'noida-sector-18',
    name: 'Noida Sector 18 (Atta Market & Mall of India)',
    shortName: 'Noida Sec 18',
    zone: 'NCR Gateways',
    zoneKey: 'ncr',
    latitude: 28.5708,
    longitude: 77.3245,
    metroStation: 'Noida Sector 18 (Blue Line)',
    metroLines: ['Blue Line'],
    famousSpecialties: ['Street Rolls', 'Gourmet Dimsums', 'Boutique Shakes', 'Microbrews'],
    tagline: 'The bustling commercial heart of Noida with massive street & mall dining',
    avgCostForTwo: 600,
    isPopularHub: true,
    pincode: '201301',
    landmarks: ['DLF Mall of India', 'Atta Market'],
  },
  {
    id: 'gurgaon-cyberhub',
    name: 'Gurgaon CyberHub & DLF Phase 2',
    shortName: 'CyberHub',
    zone: 'NCR Gateways',
    zoneKey: 'ncr',
    latitude: 28.4952,
    longitude: 77.0895,
    metroStation: 'Cyber City (Rapid Metro / Sikanderpur)',
    metroLines: ['Rapid Metro', 'Yellow Line'],
    famousSpecialties: ['Artisan Neapolitan Pizzas', 'Craft Beers', 'Pan-Asian Tapas', 'Gourmet Sliders'],
    tagline: 'India’s premier corporate dining boulevard with high-energy nightlife',
    avgCostForTwo: 1200,
    isPopularHub: true,
    pincode: '122002',
    landmarks: ['DLF Cyber City', 'CyberHub Amphitheatre'],
  },
  {
    id: 'shahpur-jat',
    name: 'Shahpur Jat (Fashion & Indie Cafes)',
    shortName: 'Shahpur Jat',
    zone: 'South Delhi',
    zoneKey: 'south',
    latitude: 28.5492,
    longitude: 77.2155,
    metroStation: 'Hauz Khas (Yellow & Magenta Line)',
    metroLines: ['Yellow Line', 'Magenta Line'],
    famousSpecialties: ['Artisan Coffee', 'Handmade Pizzas', 'Vegan Smoothies', 'Bakery Treats'],
    tagline: 'Bohemian designer alleyways packed with concept bistros and specialty coffee',
    avgCostForTwo: 650,
    isPopularHub: true,
    pincode: '110049',
    landmarks: ['Siri Fort Road', 'Dada Jungi House'],
  },
  {
    id: 'amar-colony-lajpat',
    name: 'Amar Colony (Lajpat Nagar 4)',
    shortName: 'Amar Colony',
    zone: 'South Delhi',
    zoneKey: 'south',
    latitude: 28.5665,
    longitude: 77.2425,
    metroStation: 'Moolchand (Violet Line)',
    metroLines: ['Violet Line'],
    famousSpecialties: ['Tandoori Momos', 'Afghani Burgers', 'Ram Laddoo', 'Kathi Rolls'],
    tagline: 'Delhi’s legendary evening street food hub where tandoori momos were born',
    avgCostForTwo: 350,
    isPopularHub: true,
    pincode: '110024',
    landmarks: ['Amar Colony Main Market', 'Old Double Storey'],
  },
  {
    id: 'lajpat-nagar-central',
    name: 'Lajpat Nagar Central Market',
    shortName: 'Lajpat Nagar',
    zone: 'South Delhi',
    zoneKey: 'south',
    latitude: 28.5695,
    longitude: 77.2395,
    metroStation: 'Lajpat Nagar (Violet & Pink Interchange)',
    metroLines: ['Violet Line', 'Pink Line'],
    famousSpecialties: ['Chole Bhature', 'Dolma Aunty Momos', 'Moong Dal Ram Laddoo', 'Nagpal Chole'],
    tagline: 'High-energy shopping boulevard with iconic street eats and quick-service stalls',
    avgCostForTwo: 300,
    isPopularHub: true,
    pincode: '110024',
    landmarks: ['Central Market', '3C Cinema Complex'],
  },
  {
    id: 'khan-market',
    name: 'Khan Market & Rabindra Nagar',
    shortName: 'Khan Market',
    zone: 'Central Delhi',
    zoneKey: 'central',
    latitude: 28.6002,
    longitude: 77.2275,
    metroStation: 'Khan Market (Violet Line)',
    metroLines: ['Violet Line'],
    famousSpecialties: ['Kakori Kebabs', 'Gourmet Bagels', 'Artisan Gelato', 'European Bistro Fare'],
    tagline: 'India’s most prestigious high-street retail enclave filled with boutique dining',
    avgCostForTwo: 1400,
    isPopularHub: true,
    pincode: '110003',
    landmarks: ['Middle Lane Bistros', 'Front Lane Bookstores'],
  },
  {
    id: 'pandara-road',
    name: 'Pandara Road Market (India Gate)',
    shortName: 'Pandara Road',
    zone: 'Central Delhi',
    zoneKey: 'central',
    latitude: 28.6085,
    longitude: 77.2345,
    metroStation: 'Khan Market (Violet Line) / Central Secretariat',
    metroLines: ['Violet Line', 'Yellow Line'],
    famousSpecialties: ['Butter Chicken', 'Dal Makhani', 'Mutton Rogan Josh', 'Paneer Tikka'],
    tagline: 'Delhi’s timeless midnight dining landmark for iconic North Indian feasts',
    avgCostForTwo: 950,
    isPopularHub: true,
    pincode: '110003',
    landmarks: ['Gulati Restaurant', 'Havemore', 'Bawarchi'],
  },
  {
    id: 'daryaganj-heritage',
    name: 'Daryaganj & Delhi Gate',
    shortName: 'Daryaganj',
    zone: 'Central Delhi',
    zoneKey: 'central',
    latitude: 28.6435,
    longitude: 77.2415,
    metroStation: 'Delhi Gate (Violet Line)',
    metroLines: ['Violet Line'],
    famousSpecialties: ['Original Butter Chicken', 'Tandoori Roti', 'Mutton Korma', 'Bedmi Poori'],
    tagline: 'Historic culinary trail where world-famous Tandoori dishes originated',
    avgCostForTwo: 550,
    isPopularHub: true,
    pincode: '110002',
    landmarks: ['Moti Mahal Original', 'Golcha Cinema Lane'],
  },
  {
    id: 'chawri-bazar',
    name: 'Chawri Bazar & Nai Sarak',
    shortName: 'Chawri Bazar',
    zone: 'Central Delhi',
    zoneKey: 'central',
    latitude: 28.6495,
    longitude: 77.2285,
    metroStation: 'Chawri Bazar (Yellow Line)',
    metroLines: ['Yellow Line'],
    famousSpecialties: ['Kulfi Falooda', 'Bedmi Poori Nagori', 'Hing Kachori', 'Fruit Chaat'],
    tagline: 'Centuries-old lanes home to India’s most beloved sweetshops and street breakfast',
    avgCostForTwo: 200,
    isPopularHub: true,
    pincode: '110006',
    landmarks: ['Kuremal Mohanlal Kulfi', 'Shyam Sweets'],
  },
  {
    id: 'paharganj-main-bazar',
    name: 'Paharganj (Main Bazar & Imperial)',
    shortName: 'Paharganj',
    zone: 'Central Delhi',
    zoneKey: 'central',
    latitude: 28.6442,
    longitude: 77.2155,
    metroStation: 'New Delhi (Yellow Line & Airport Line)',
    metroLines: ['Yellow Line', 'Airport Express Line'],
    famousSpecialties: ['Shakshuka & Hummus', 'Nutella Pancakes', 'Rooftop Cafes', 'Sita Ram Chole Bhature'],
    tagline: 'Legendary backpacker haven packed with international rooftop cafes and street eats',
    avgCostForTwo: 350,
    isPopularHub: true,
    pincode: '110055',
    landmarks: ['Main Bazar Market', 'Imperial Cinema'],
  },
  {
    id: 'subhash-nagar-pacific',
    name: 'Subhash Nagar & Pacific Mall Food Street',
    shortName: 'Subhash Nagar',
    zone: 'West Delhi',
    zoneKey: 'west',
    latitude: 28.6395,
    longitude: 77.1085,
    metroStation: 'Subhash Nagar (Blue Line)',
    metroLines: ['Blue Line'],
    famousSpecialties: ['Afghani Malai Chaap', 'Tandoori Burgers', 'Kulhad Pizza', 'Mojitos'],
    tagline: 'Buzzing West Delhi hangout filled with neon-lit street food stalls and malls',
    avgCostForTwo: 350,
    isPopularHub: false,
    pincode: '110027',
    landmarks: ['Pacific Mall Tag', 'Ajay Enclave'],
  },
  {
    id: 'vikaspuri-pvr',
    name: 'Vikaspuri (PVR Complex & Community Centre)',
    shortName: 'Vikaspuri',
    zone: 'West Delhi',
    zoneKey: 'west',
    latitude: 28.6385,
    longitude: 77.0785,
    metroStation: 'Janakpuri West (Blue & Magenta Interchange)',
    metroLines: ['Blue Line', 'Magenta Line'],
    famousSpecialties: ['Tandoori Soya Chaap', 'Paneer Tikka Roll', 'Cold Coffee', 'Pasta Platter'],
    tagline: 'Residential foodie hub with open-air plaza cafes and midnight snack counters',
    avgCostForTwo: 400,
    isPopularHub: false,
    pincode: '110018',
    landmarks: ['PVR Vikaspuri', 'F Block Market'],
  },
  {
    id: 'uttam-nagar-east',
    name: 'Uttam Nagar (Arya Samaj Road & Metro Street)',
    shortName: 'Uttam Nagar',
    zone: 'West Delhi',
    zoneKey: 'west',
    latitude: 28.6215,
    longitude: 77.0585,
    metroStation: 'Uttam Nagar East (Blue Line)',
    metroLines: ['Blue Line'],
    famousSpecialties: ['Gravy Momos', 'Pav Bhaji', 'Chole Kulche', 'Fruit Beer'],
    tagline: 'High-density transit street with hundreds of budget-friendly takeaway food counters',
    avgCostForTwo: 250,
    isPopularHub: false,
    pincode: '110059',
    landmarks: ['Arya Samaj Road', 'Metro Pillar 650'],
  },
  {
    id: 'rohini-sector-7-8',
    name: 'Rohini Sector 7 & 8 Food Street',
    shortName: 'Rohini Sec 7-8',
    zone: 'North-West Delhi',
    zoneKey: 'northwest',
    latitude: 28.7095,
    longitude: 77.1195,
    metroStation: 'Rohini East (Red Line)',
    metroLines: ['Red Line'],
    famousSpecialties: ['Overload Monster Shakes', 'Kurkure Paneer Momos', 'Cheesy Pizza Fries', 'Waffles'],
    tagline: 'The North-West youth capital famous for evening snacks, shakes and viral street foods',
    avgCostForTwo: 350,
    isPopularHub: true,
    pincode: '110085',
    landmarks: ['Sector 7 Market', 'M2K Cinema Complex'],
  },
  {
    id: 'rohini-sector-13-14',
    name: 'Rohini Sector 13 & 14 (DC Chowk & Ring Road Mall)',
    shortName: 'Rohini Sec 13-14',
    zone: 'North-West Delhi',
    zoneKey: 'northwest',
    latitude: 28.7215,
    longitude: 77.1325,
    metroStation: 'Rohini West (Red Line)',
    metroLines: ['Red Line'],
    famousSpecialties: ['North Indian Thalis', 'Wood-fired Pizzas', 'Artisan Coffee', 'Kulfi Falooda'],
    tagline: 'Family dining and student adda surrounding DC Chowk and community centers',
    avgCostForTwo: 450,
    isPopularHub: false,
    pincode: '110085',
    landmarks: ['DC Chowk Market', 'Ring Road Mall'],
  },
  {
    id: 'mayur-vihar-phase-2',
    name: 'Mayur Vihar Phase 2 (Pocket B Shopping Centre)',
    shortName: 'Mayur Vihar 2',
    zone: 'East Delhi',
    zoneKey: 'east',
    latitude: 28.6185,
    longitude: 77.3095,
    metroStation: 'Mayur Vihar Phase 1 / Trilokpuri Sanjay Lake',
    metroLines: ['Pink Line'],
    famousSpecialties: ['South Indian Thali', 'Kathi Rolls', 'Chilli Garlic Chowmein', 'Cold Coffee'],
    tagline: 'Cozy neighbourhood center filled with family diners and evening snack stalls',
    avgCostForTwo: 350,
    isPopularHub: false,
    pincode: '110091',
    landmarks: ['Pocket B Market', 'Neelam Mata Mandir Chowk'],
  },
  {
    id: 'krishna-nagar-lal-quarter',
    name: 'Krishna Nagar (Lal Quarter Food Market)',
    shortName: 'Krishna Nagar',
    zone: 'East Delhi',
    zoneKey: 'east',
    latitude: 28.6625,
    longitude: 77.2795,
    metroStation: 'Krishna Nagar (Pink Line)',
    metroLines: ['Pink Line'],
    famousSpecialties: ['Bombay Pav Bhaji', 'Rabri Jalebi', 'Aloo Chaat', 'Afghani Soya Chaap'],
    tagline: 'Trans-Yamuna’s premier shopping street packed with historic street food vendors',
    avgCostForTwo: 300,
    isPopularHub: true,
    pincode: '110051',
    landmarks: ['Lal Quarter Market', 'Ghondly Chowk'],
  },
  {
    id: 'indirapuram-habitat',
    name: 'Indirapuram (Habitat Centre & Vaibhav Khand)',
    shortName: 'Indirapuram',
    zone: 'NCR Gateways',
    zoneKey: 'ncr',
    latitude: 28.6415,
    longitude: 77.3715,
    metroStation: 'Vaishali (Blue Line) / Electronic City (Blue Line)',
    metroLines: ['Blue Line'],
    famousSpecialties: ['Craft Mocktails', 'Tandoori Kebabs', 'Thin Crust Pizzas', 'Cold Brews'],
    tagline: 'Modern township promenade with open-air dining plazas and high-energy cafes',
    avgCostForTwo: 600,
    isPopularHub: true,
    pincode: '201014',
    landmarks: ['Indirapuram Habitat Centre', 'Aditya Mall'],
  },
  {
    id: 'gurgaon-sector-29',
    name: 'Gurgaon Sector 29 Food & Brewery Boulevard',
    shortName: 'Gurgaon Sec 29',
    zone: 'NCR Gateways',
    zoneKey: 'ncr',
    latitude: 28.4685,
    longitude: 77.0625,
    metroStation: 'IFFCO Chowk (Yellow Line)',
    metroLines: ['Yellow Line'],
    famousSpecialties: ['Craft Beer', 'BBQ Chicken Wings', 'Tandoori Platters', 'Gourmet Sliders'],
    tagline: 'NCR’s renowned open-air brewery strip with high-octane live music and dining',
    avgCostForTwo: 1100,
    isPopularHub: true,
    pincode: '122001',
    landmarks: ['Leisure Valley Park', 'Sector 29 Market'],
  },
  {
    id: 'golf-course-road',
    name: 'Golf Course Road & One Horizon Centre',
    shortName: 'Golf Course Rd',
    zone: 'NCR Gateways',
    zoneKey: 'ncr',
    latitude: 28.4725,
    longitude: 77.0985,
    metroStation: 'Sector 42-43 (Rapid Metro)',
    metroLines: ['Rapid Metro'],
    famousSpecialties: ['Artisan Bakery Treats', 'Authentic Sushi', 'Italian Risotto', 'Specialty Matcha'],
    tagline: 'Ultra-modern luxury dining district featuring award-winning chefs and lounges',
    avgCostForTwo: 1500,
    isPopularHub: true,
    pincode: '122002',
    landmarks: ['One Horizon Centre', 'DLF South Point Mall'],
  },
];

export interface DelhiCoverageStats {
  totalLocations: number;
  coveredCount: number; // 3+ cafes
  partialCount: number; // 1-2 cafes
  uncoveredCount: number; // 0 cafes
  coveragePercentage: number;
}

/**
 * Computes coverage statistics across all Delhi NCR locations.
 * Matches restaurants by name, address, landmark, city, and GPS coordinates.
 */
export function computeDelhiCoverage(restaurants: any[]): {
  stats: DelhiCoverageStats;
  locationCounts: Record<string, number>;
  coveredLocations: DelhiLocation[];
  partialLocations: DelhiLocation[];
  uncoveredLocations: DelhiLocation[];
} {
  const counts: Record<string, number> = {};

  for (const loc of DELHI_LOCATIONS) {
    counts[loc.id] = 0;
  }

  for (const r of restaurants) {
    const fullText = `${r.name || ''} ${r.landmark || ''} ${r.address_line1 || ''} ${r.city || ''}`.toLowerCase();
    
    // Check if restaurant is explicitly in an area
    let matched = false;
    for (const loc of DELHI_LOCATIONS) {
      const matchKey = loc.shortName.toLowerCase();
      const nameKey = loc.name.toLowerCase();
      if (fullText.includes(matchKey) || fullText.includes(nameKey)) {
        counts[loc.id] = (counts[loc.id] || 0) + 1;
        matched = true;
        break;
      }
    }

    // Geolocation fallback matching if text didn't trigger
    if (!matched && r.latitude && r.longitude) {
      for (const loc of DELHI_LOCATIONS) {
        const dLat = Math.abs(r.latitude - loc.latitude);
        const dLng = Math.abs(r.longitude - loc.longitude);
        if (dLat < 0.015 && dLng < 0.015) { // ~1.5 km
          counts[loc.id] = (counts[loc.id] || 0) + 1;
          break;
        }
      }
    }
  }

  const covered: DelhiLocation[] = [];
  const partial: DelhiLocation[] = [];
  const uncovered: DelhiLocation[] = [];

  for (const loc of DELHI_LOCATIONS) {
    const c = counts[loc.id] || 0;
    if (c >= 3) {
      covered.push(loc);
    } else if (c > 0) {
      partial.push(loc);
    } else {
      uncovered.push(loc);
    }
  }

  const total = DELHI_LOCATIONS.length;
  const coveragePercentage = total > 0 ? Math.round((covered.length / total) * 100) : 0;

  return {
    stats: {
      totalLocations: total,
      coveredCount: covered.length,
      partialCount: partial.length,
      uncoveredCount: uncovered.length,
      coveragePercentage,
    },
    locationCounts: counts,
    coveredLocations: covered,
    partialLocations: partial,
    uncoveredLocations: uncovered,
  };
}
