import { Restaurant, MenuCategory, MenuItem } from '../types/database';

export const EXTRA_ZONE_RESTAURANTS: Restaurant[] = [
  {
    id: '22222222-0000-4000-8000-000000000001',
    name: 'Big Yellow Door (BYD)',
    slug: 'big-yellow-door-hudson-lane',
    short_description: 'Legendary student hotspot in Hudson Lane famed for loaded Cheesy Baked Pasta, Bomb Burgers, and monster shakes.',
    long_description: 'Big Yellow Door (BYD) is the defining landmark cafe of Delhi University North Campus. Featuring warm wooden interiors, fairy-lit corners, high-speed Wi-Fi, and generous study booths, it is bustling with college students, project groups, and faculty. It offers delicious, pocket-friendly comfort food under ₹200.',
    cuisine_types: ['Cafe', 'Italian', 'Fast Food', 'Beverages', 'Desserts'],
    meal_types: ['Lunch', 'Snacks', 'Dinner', 'Late Night'],
    price_range: '₹',
    average_cost_for_two: 350,
    address_line1: '2521, 2nd Floor, Hudson Lane, Kingsway Camp, GTB Nagar',
    address_line2: 'Near North Campus',
    landmark: 'Opposite NDPL Office, Hudson Lane',
    city: 'North Campus, New Delhi',
    state: 'Delhi',
    pincode: '110009',
    country: 'India',
    latitude: 28.6953,
    longitude: 77.2048,
    phone: '+91 70422 94297',
    whatsapp_number: '+91 70422 94297',
    cover_image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1000&auto=format&fit=crop&q=80',
    is_open: true,
    opening_hours: {
      Monday: { open: '11:00 AM', close: '11:00 PM', is_closed: false },
      Tuesday: { open: '11:00 AM', close: '11:00 PM', is_closed: false },
      Wednesday: { open: '11:00 AM', close: '11:00 PM', is_closed: false },
      Thursday: { open: '11:00 AM', close: '11:00 PM', is_closed: false },
      Friday: { open: '11:00 AM', close: '11:30 PM', is_closed: false },
      Saturday: { open: '11:00 AM', close: '11:30 PM', is_closed: false },
      Sunday: { open: '11:00 AM', close: '11:00 PM', is_closed: false },
    },
    delivery_available: true,
    takeaway_available: true,
    dine_in_available: true,
    facilities: ['Free WiFi', 'Power Outlets', 'Air Conditioned', 'Indoor Seating', 'Student Discount Friendly', 'Board Games'],
    dietary_options: ['Pure Veg', 'Vegan Options'],
    rating_avg: 4.6,
    rating_count: 2480,
    is_featured: true,
    is_active: true,
    is_temporarily_closed: false,
    known_for_dishes: ['BYD Cheese Bomb Burger', 'Baked Cheesy Alfredo Pasta', 'Ferrero Rocher Monster Shake', 'Spicy Peri Peri Fries'],
    best_for_tags: ['Studying', 'Groups', 'Budget', 'Coffee', 'Late Night'],
    ambience_tags: ['Lively & Social', 'Modern & Trendy'],
    nearby_landmarks: ['Delhi University North Campus (3 min walk)', 'GTB Nagar Metro Gate 4', 'Hudson Lane Food Strip'],
    heritage_area: false,
    specialty_dishes: ['BYD Cheese Bomb Burger', 'Baked Cheesy Alfredo Pasta', 'Ferrero Rocher Shake'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22222222-0000-4000-8000-000000000002',
    name: 'Ricos Cafe & Bistro',
    slug: 'ricos-cafe-hudson-lane',
    short_description: 'Chic European-styled university cafe famous for artisanal waffles, creamy risottos, and assignment-friendly work tables.',
    long_description: 'With cozy bookshelf-lined walls, vintage framed artwork, and soothing jazz, Ricos is a beloved second home for Delhi University students and book lovers. Features abundant power plugs, high-speed Wi-Fi, and generous artisan coffee portions.',
    cuisine_types: ['Cafe', 'Italian', 'Continental', 'Desserts', 'Coffee'],
    meal_types: ['Breakfast', 'Lunch', 'Snacks', 'Dinner'],
    price_range: '₹₹',
    average_cost_for_two: 500,
    address_line1: '2526, 1st Floor, Hudson Lane, Kingsway Camp, GTB Nagar',
    address_line2: 'North Campus',
    landmark: 'Above Axis Bank ATM',
    city: 'North Campus, New Delhi',
    state: 'Delhi',
    pincode: '110009',
    country: 'India',
    latitude: 28.6948,
    longitude: 77.2052,
    phone: '+91 99990 01122',
    whatsapp_number: '+91 99990 01122',
    cover_image_url: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=1000&auto=format&fit=crop&q=80',
    is_open: true,
    opening_hours: {
      Monday: { open: '10:30 AM', close: '11:00 PM', is_closed: false },
      Tuesday: { open: '10:30 AM', close: '11:00 PM', is_closed: false },
      Wednesday: { open: '10:30 AM', close: '11:00 PM', is_closed: false },
      Thursday: { open: '10:30 AM', close: '11:00 PM', is_closed: false },
      Friday: { open: '10:30 AM', close: '11:30 PM', is_closed: false },
      Saturday: { open: '10:30 AM', close: '11:30 PM', is_closed: false },
      Sunday: { open: '10:30 AM', close: '11:00 PM', is_closed: false },
    },
    delivery_available: true,
    takeaway_available: true,
    dine_in_available: true,
    facilities: ['Free WiFi', 'Power Outlets', 'Quiet Corners', 'Air Conditioned', 'Reading Library'],
    dietary_options: ['Pure Veg', 'Vegan Options'],
    rating_avg: 4.5,
    rating_count: 1820,
    is_featured: true,
    is_active: true,
    is_temporarily_closed: false,
    known_for_dishes: ['Belgian Chocolate Waffles', 'Penne Arrabbiata', 'Apple Cinnamon Thick Shake', 'Hummus & Pita Platter'],
    best_for_tags: ['Studying', 'Date Night', 'Coffee', 'Budget'],
    ambience_tags: ['Cozy & Quiet', 'Modern & Trendy'],
    nearby_landmarks: ['Faculty of Arts DU', 'Vishwa Vidyalaya Metro', 'Hudson Lane Main Market'],
    heritage_area: false,
    specialty_dishes: ['Belgian Waffle', 'Penne Arrabbiata', 'Apple Cinnamon Shake'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22222222-0000-4000-8000-000000000003',
    name: "Tom Uncle's Maggi Point",
    slug: 'tom-uncles-maggi-point',
    short_description: 'Historic 45-year-old DU student institution serving 50+ varieties of butter-loaded Maggi, cheesy sodas, and chai.',
    long_description: 'Founded in 1978 on Chattra Marg near Ramjas College, Tom Uncle is an indelible part of North Campus campus life. Generations of DU alumni swear by his butter-drenched spicy Maggi recipes cooked live on big tawa burners and served with chilled sodas.',
    cuisine_types: ['Street Food', 'Fast Food', 'Snacks', 'Chai'],
    meal_types: ['Breakfast', 'Lunch', 'Snacks', 'Late Night'],
    price_range: '₹',
    average_cost_for_two: 150,
    address_line1: 'Near Ramjas College, Chattra Marg, Maurice Nagar, University Enclave',
    address_line2: '',
    landmark: 'Opposite Ramjas College Ground',
    city: 'North Campus, New Delhi',
    state: 'Delhi',
    pincode: '110007',
    country: 'India',
    latitude: 28.6898,
    longitude: 77.2115,
    phone: '+91 98114 41122',
    whatsapp_number: '+91 98114 41122',
    cover_image_url: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=1000&auto=format&fit=crop&q=80',
    is_open: true,
    opening_hours: {
      Monday: { open: '09:00 AM', close: '11:00 PM', is_closed: false },
      Tuesday: { open: '09:00 AM', close: '11:00 PM', is_closed: false },
      Wednesday: { open: '09:00 AM', close: '11:00 PM', is_closed: false },
      Thursday: { open: '09:00 AM', close: '11:00 PM', is_closed: false },
      Friday: { open: '09:00 AM', close: '11:30 PM', is_closed: false },
      Saturday: { open: '09:00 AM', close: '11:30 PM', is_closed: false },
      Sunday: { open: '09:00 AM', close: '11:00 PM', is_closed: false },
    },
    delivery_available: false,
    takeaway_available: true,
    dine_in_available: true,
    facilities: ['Outdoor Seating', 'Quick Service', 'Budget Meals Under ₹100', 'Campus Vibe'],
    dietary_options: ['Pure Veg'],
    rating_avg: 4.7,
    rating_count: 5120,
    is_featured: true,
    is_active: true,
    is_temporarily_closed: false,
    known_for_dishes: ['Double Butter Masala Maggi', 'Cheese Corn Maggi', 'Tandoori Paneer Maggi', 'Masala Lemon Banta'],
    best_for_tags: ['Budget', 'Groups', 'Breakfast', 'Late Night'],
    ambience_tags: ['Lively & Social', 'Outdoor Seating Available'],
    nearby_landmarks: ['Ramjas College (1 min walk)', 'Kirori Mal College', 'Delhi School of Economics'],
    heritage_area: false,
    specialty_dishes: ['Double Butter Masala Maggi', 'Cheese Corn Maggi', 'Masala Banta'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22222222-0000-4000-8000-000000000004',
    name: 'AMA Cafe',
    slug: 'ama-cafe-majnu-ka-tilla',
    short_description: 'Cozy Himalayan mountain-styled cafe famed for blueberry pancakes, pour-over coffees, and warm wooden aesthetics.',
    long_description: 'Nestled in the bustling lanes of Majnu Ka Tilla near DU North Campus, AMA Cafe is a legendary Himalayan sanctuary. With hand-crafted timber furniture, warm mountain vibes, artisan roasts, and house-made bakery delights, it is an irresistible hangout for creative students and coffee aficionados.',
    cuisine_types: ['Cafe', 'Continental', 'Bakery', 'Coffee', 'Desserts'],
    meal_types: ['Breakfast', 'Lunch', 'Snacks', 'Dinner'],
    price_range: '₹₹',
    average_cost_for_two: 550,
    address_line1: 'House 6, New Aruna Nagar, Majnu Ka Tilla',
    address_line2: 'Near North Campus',
    landmark: 'Near Tibetan Monastery, Majnu Ka Tilla',
    city: 'North Campus, New Delhi',
    state: 'Delhi',
    pincode: '110054',
    country: 'India',
    latitude: 28.7029,
    longitude: 77.2285,
    phone: '+91 11 2381 2289',
    whatsapp_number: '+91 11 2381 2289',
    cover_image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1000&auto=format&fit=crop&q=80',
    is_open: true,
    opening_hours: {
      Monday: { open: '08:00 AM', close: '10:00 PM', is_closed: false },
      Tuesday: { open: '08:00 AM', close: '10:00 PM', is_closed: false },
      Wednesday: { open: '08:00 AM', close: '10:00 PM', is_closed: false },
      Thursday: { open: '08:00 AM', close: '10:00 PM', is_closed: false },
      Friday: { open: '08:00 AM', close: '10:00 PM', is_closed: false },
      Saturday: { open: '08:00 AM', close: '10:00 PM', is_closed: false },
      Sunday: { open: '08:00 AM', close: '10:00 PM', is_closed: false },
    },
    delivery_available: false,
    takeaway_available: true,
    dine_in_available: true,
    facilities: ['Free WiFi', 'Power Outlets', 'Air Conditioned', 'Mountain Ambience', 'Fresh Bakery Counter'],
    dietary_options: ['Pure Veg', 'Vegan Options'],
    rating_avg: 4.8,
    rating_count: 6240,
    is_featured: true,
    is_active: true,
    is_temporarily_closed: false,
    known_for_dishes: ['Fluffy Blueberry Pancakes', 'Himalayan Pour-over Coffee', 'Classic Tiramisu', 'Avocado & Scrambled Eggs'],
    best_for_tags: ['Coffee', 'Breakfast', 'Studying', 'Date Night', 'Views'],
    ambience_tags: ['Cozy & Quiet', 'Modern & Trendy', 'Traditional & Heritage'],
    nearby_landmarks: ['Majnu Ka Tilla Tibetan Monastery', 'Vidhan Sabha Metro Station', 'DU North Campus Gate'],
    heritage_area: false,
    specialty_dishes: ['Blueberry Pancakes', 'Himalayan Pour-Over', 'Classic Tiramisu'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22222222-0000-4000-8000-000000000005',
    name: 'Chache Di Hatti',
    slug: 'chache-di-hatti-kamla-nagar',
    short_description: '70-year-old historic North Campus legend serving Delhi’s finest Rawalpindi Chole Bhature with stuffed aloo kulchas.',
    long_description: 'Operating in Kamla Nagar since 1953, Chache Di Hatti is a morning ritual for thousands of Delhi University students, professors, and heritage food lovers. Their aloo-stuffed piping-hot bhaturas are soft, non-greasy, and paired with intensely spiced black chickpeas and tangy pickled green chillies.',
    cuisine_types: ['North Indian', 'Punjabi Breakfast', 'Street Food'],
    meal_types: ['Breakfast', 'Lunch'],
    price_range: '₹',
    average_cost_for_two: 180,
    address_line1: 'D-32, Bungalow Road, Kamla Nagar',
    address_line2: 'North Campus',
    landmark: 'Near Hansraj College Gate',
    city: 'North Campus, New Delhi',
    state: 'Delhi',
    pincode: '110007',
    country: 'India',
    latitude: 28.6821,
    longitude: 77.2036,
    phone: '+91 98113 89912',
    whatsapp_number: '+91 98113 89912',
    cover_image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=1000&auto=format&fit=crop&q=80',
    is_open: true,
    opening_hours: {
      Monday: { open: '09:30 AM', close: '04:00 PM', is_closed: false },
      Tuesday: { open: '09:30 AM', close: '04:00 PM', is_closed: false },
      Wednesday: { open: '09:30 AM', close: '04:00 PM', is_closed: false },
      Thursday: { open: '09:30 AM', close: '04:00 PM', is_closed: false },
      Friday: { open: '09:30 AM', close: '04:00 PM', is_closed: false },
      Saturday: { open: '09:30 AM', close: '04:00 PM', is_closed: false },
      Sunday: { open: '09:30 AM', close: '04:00 PM', is_closed: false },
    },
    delivery_available: false,
    takeaway_available: true,
    dine_in_available: true,
    facilities: ['Counter Service', 'Quick Service', 'Heritage Eatery', 'Takeout'],
    dietary_options: ['Pure Veg'],
    rating_avg: 4.8,
    rating_count: 7890,
    is_featured: true,
    is_active: true,
    is_temporarily_closed: false,
    known_for_dishes: ['Rawalpindi Chole Bhature', 'Aloo Stuffed Bhatura Plate', 'Desi Sweet Lassi'],
    best_for_tags: ['Breakfast', 'Budget', 'Traditional Food'],
    ambience_tags: ['Traditional & Heritage', 'Lively & Social'],
    nearby_landmarks: ['Hansraj College', 'Kamla Nagar Market', 'Vishwa Vidyalaya Metro'],
    heritage_area: false,
    specialty_dishes: ['Rawalpindi Chole Bhature', 'Aloo Bhatura Plate', 'Thick Lassi'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22222222-0000-4000-8000-000000000006',
    name: 'United Coffee House',
    slug: 'united-coffee-house-connaught-place',
    short_description: '80-year-old colonial heritage restaurant in CP Inner Circle famed for signature Cona Coffee, Cheese Balls, and Victorian decor.',
    long_description: 'Established in 1942, United Coffee House is an iconic institution in the heart of Connaught Place. With ornate crystal chandeliers, vintage portraits, plush leather armchairs, and formal uniformed staff, it has hosted presidents, artists, and diplomats for over eight decades.',
    cuisine_types: ['Cafe', 'Continental', 'North Indian', 'European', 'Coffee'],
    meal_types: ['Breakfast', 'Lunch', 'Snacks', 'Dinner'],
    price_range: '₹₹₹',
    average_cost_for_two: 1400,
    address_line1: 'E-15, Inner Circle, Connaught Place',
    address_line2: '',
    landmark: 'Near Rajiv Chowk Metro Gate 3',
    city: 'Connaught Place, New Delhi',
    state: 'Delhi',
    pincode: '110001',
    country: 'India',
    latitude: 28.6315,
    longitude: 77.2198,
    phone: '+91 11 2341 1697',
    whatsapp_number: '+91 11 2341 1697',
    cover_image_url: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=1000&auto=format&fit=crop&q=80',
    is_open: true,
    opening_hours: {
      Monday: { open: '11:00 AM', close: '11:30 PM', is_closed: false },
      Tuesday: { open: '11:00 AM', close: '11:30 PM', is_closed: false },
      Wednesday: { open: '11:00 AM', close: '11:30 PM', is_closed: false },
      Thursday: { open: '11:00 AM', close: '11:30 PM', is_closed: false },
      Friday: { open: '11:00 AM', close: '11:30 PM', is_closed: false },
      Saturday: { open: '11:00 AM', close: '11:30 PM', is_closed: false },
      Sunday: { open: '11:00 AM', close: '11:30 PM', is_closed: false },
    },
    delivery_available: true,
    takeaway_available: true,
    dine_in_available: true,
    facilities: ['Air Conditioned', 'Valet Parking', 'Fine Dining', 'Heritage Interior', 'Full Bar', 'Table Reservations'],
    dietary_options: ['Pure Veg', 'Vegan Options', 'Halal'],
    rating_avg: 4.6,
    rating_count: 5310,
    is_featured: true,
    is_active: true,
    is_temporarily_closed: false,
    known_for_dishes: ['Special Cona Blend Coffee', 'UCH Cheese Balls', 'Chicken A La Kiev', 'Railway Mutton Curry', 'Fish Finger Orly'],
    best_for_tags: ['Coffee', 'Traditional Food', 'Date Night', 'Views'],
    ambience_tags: ['Traditional & Heritage', 'Romantic & Intimate', 'Cozy & Quiet'],
    nearby_landmarks: ['Rajiv Chowk Metro Gate 3', 'Central Park CP', 'Palika Bazar'],
    heritage_area: true,
    specialty_dishes: ['Special Cona Coffee', 'UCH Cheese Balls', 'Chicken A La Kiev'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22222222-0000-4000-8000-000000000007',
    name: "Wenger's & Wenger's Deli",
    slug: 'wengers-deli-connaught-place',
    short_description: '95-year-old historic Swiss bakery and deli in CP serving legendary Shami Kebabs, Nutella waffles, and express office lunches.',
    long_description: 'Founded in 1926, Wenger’s is Delhi’s oldest premier bakery and delicatessen. Located in A Block of Connaught Place, it is famous for its melt-in-mouth Shami kebabs, chicken patties, gourmet panini, and chocolate waffles, making it the top destination for quick office lunch breaks and afternoon tea snacks.',
    cuisine_types: ['Bakery', 'Cafe', 'Fast Food', 'Desserts', 'Coffee'],
    meal_types: ['Breakfast', 'Lunch', 'Snacks'],
    price_range: '₹₹',
    average_cost_for_two: 450,
    address_line1: 'A-16, Radial Road 3, A Block, Connaught Place',
    address_line2: '',
    landmark: 'Near Odeon Cinema, Inner Circle',
    city: 'Connaught Place, New Delhi',
    state: 'Delhi',
    pincode: '110001',
    country: 'India',
    latitude: 28.6328,
    longitude: 77.2185,
    phone: '+91 11 2332 4403',
    whatsapp_number: '+91 11 2332 4403',
    cover_image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1000&auto=format&fit=crop&q=80',
    is_open: true,
    opening_hours: {
      Monday: { open: '10:30 AM', close: '08:00 PM', is_closed: false },
      Tuesday: { open: '10:30 AM', close: '08:00 PM', is_closed: false },
      Wednesday: { open: '10:30 AM', close: '08:00 PM', is_closed: false },
      Thursday: { open: '10:30 AM', close: '08:00 PM', is_closed: false },
      Friday: { open: '10:30 AM', close: '08:00 PM', is_closed: false },
      Saturday: { open: '10:30 AM', close: '08:00 PM', is_closed: false },
      Sunday: { open: '10:30 AM', close: '08:00 PM', is_closed: false },
    },
    delivery_available: true,
    takeaway_available: true,
    dine_in_available: true,
    facilities: ['Quick Service Counter', 'Takeout', 'Express Lunch', 'Bakery Fresh'],
    dietary_options: ['Pure Veg', 'Vegan Options'],
    rating_avg: 4.7,
    rating_count: 8940,
    is_featured: true,
    is_active: true,
    is_temporarily_closed: false,
    known_for_dishes: ['Mutton Shami Kebab', 'Nutella Waffle', 'Chicken Patty', 'Black Forest Pastry', 'Panini Sandwich'],
    best_for_tags: ['Breakfast', 'Traditional Food', 'Coffee', 'Budget'],
    ambience_tags: ['Traditional & Heritage', 'Lively & Social'],
    nearby_landmarks: ['Regal Building CP', 'Janpath Flea Market', 'Rajiv Chowk Metro Gate 7'],
    heritage_area: true,
    specialty_dishes: ['Mutton Shami Kebab', 'Nutella Waffle', 'Chicken Patty'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22222222-0000-4000-8000-000000000008',
    name: 'Social Hauz Khas (HKV)',
    slug: 'social-hauz-khas-village',
    short_description: 'Iconic multi-level urban cafe and co-working hub directly overlooking 14th-century Hauz Khas lake & monument ruins.',
    long_description: 'Social Hauz Khas revolutionized Delhi dining by melding a vibrant bohemian co-working cafe by day with an energetic lounge by night. Spanning several floors of reclaimed timber, industrial steel, and unobstructed panoramic vistas of the 14th-century water reservoir and Feroz Shah madrasa ruins.',
    cuisine_types: ['Cafe', 'Continental', 'North Indian', 'Fusion', 'Cocktails'],
    meal_types: ['Lunch', 'Snacks', 'Dinner', 'Late Night'],
    price_range: '₹₹',
    average_cost_for_two: 800,
    address_line1: '9A & 12, Hauz Khas Village',
    address_line2: '',
    landmark: 'Overlooking Hauz Khas Fort & Lake',
    city: 'Hauz Khas, New Delhi',
    state: 'Delhi',
    pincode: '110016',
    country: 'India',
    latitude: 28.5539,
    longitude: 77.1942,
    phone: '+91 78386 52814',
    whatsapp_number: '+91 78386 52814',
    cover_image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1000&auto=format&fit=crop&q=80',
    is_open: true,
    opening_hours: {
      Monday: { open: '11:00 AM', close: '01:00 AM', is_closed: false },
      Tuesday: { open: '11:00 AM', close: '01:00 AM', is_closed: false },
      Wednesday: { open: '11:00 AM', close: '01:00 AM', is_closed: false },
      Thursday: { open: '11:00 AM', close: '01:00 AM', is_closed: false },
      Friday: { open: '11:00 AM', close: '01:00 AM', is_closed: false },
      Saturday: { open: '11:00 AM', close: '01:00 AM', is_closed: false },
      Sunday: { open: '11:00 AM', close: '01:00 AM', is_closed: false },
    },
    delivery_available: true,
    takeaway_available: true,
    dine_in_available: true,
    facilities: ['Free WiFi', 'Power Outlets', 'Lake & Monument View', 'Outdoor Balcony Seating', 'Live DJ', 'Co-working Desks'],
    dietary_options: ['Pure Veg', 'Vegan Options'],
    rating_avg: 4.6,
    rating_count: 9810,
    is_featured: true,
    is_active: true,
    is_temporarily_closed: false,
    known_for_dishes: ['Death By Chocolate', 'Butter Chicken Biryani', 'Chilli Cheese Toast', 'Dhingra Special Chilli Paneer'],
    best_for_tags: ['Views', 'Groups', 'Date Night', 'Late Night', 'Studying'],
    ambience_tags: ['Lively & Social', 'Modern & Trendy', 'Outdoor Seating Available'],
    nearby_landmarks: ['Hauz Khas 14th Century Fort & Lake', 'Deer Park Entrance', 'Hauz Khas Village Main Gate'],
    heritage_area: true,
    specialty_dishes: ['Death By Chocolate', 'Butter Chicken Biryani', 'Chilli Cheese Toast'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22222222-0000-4000-8000-000000000009',
    name: 'Coast Cafe at Ogaan',
    slug: 'coast-cafe-hauz-khas-village',
    short_description: 'Serene bohemian rooftop bistro in Hauz Khas overlooking lush trees and monuments, famed for coastal Kerala curries and appams.',
    long_description: 'Perched above Ogaan boutique in Hauz Khas Village, Coast Cafe is a sun-drenched, white-washed oasis featuring tall French windows, tropical plants, and airy balconies. Celebrated for its light coastal curries, crispy appams, and pour-over coffee.',
    cuisine_types: ['Cafe', 'South Indian Coastal', 'Continental', 'Seafood', 'Coffee'],
    meal_types: ['Lunch', 'Snacks', 'Dinner'],
    price_range: '₹₹₹',
    average_cost_for_two: 1200,
    address_line1: '2nd & 3rd Floor, H2, Hauz Khas Village',
    address_line2: '',
    landmark: 'Above Ogaan Boutique',
    city: 'Hauz Khas, New Delhi',
    state: 'Delhi',
    pincode: '110016',
    country: 'India',
    latitude: 28.5535,
    longitude: 77.1939,
    phone: '+91 11 4160 1714',
    whatsapp_number: '+91 11 4160 1714',
    cover_image_url: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=1000&auto=format&fit=crop&q=80',
    is_open: true,
    opening_hours: {
      Monday: { open: '12:00 PM', close: '11:00 PM', is_closed: false },
      Tuesday: { open: '12:00 PM', close: '11:00 PM', is_closed: false },
      Wednesday: { open: '12:00 PM', close: '11:00 PM', is_closed: false },
      Thursday: { open: '12:00 PM', close: '11:00 PM', is_closed: false },
      Friday: { open: '12:00 PM', close: '11:00 PM', is_closed: false },
      Saturday: { open: '12:00 PM', close: '11:00 PM', is_closed: false },
      Sunday: { open: '12:00 PM', close: '11:00 PM', is_closed: false },
    },
    delivery_available: true,
    takeaway_available: true,
    dine_in_available: true,
    facilities: ['Air Conditioned', 'Balcony Seating', 'Romantic Vibe', 'Wi-Fi', 'Table Reservation'],
    dietary_options: ['Pure Veg', 'Vegan Options', 'Gluten-Free Options'],
    rating_avg: 4.7,
    rating_count: 2150,
    is_featured: true,
    is_active: true,
    is_temporarily_closed: false,
    known_for_dishes: ['Prawn Moilee with Appams', 'Avocado & Tomato Tartine', 'Vegetable Stew', 'Cold Brew Tonic'],
    best_for_tags: ['Views', 'Date Night', 'Coffee'],
    ambience_tags: ['Romantic & Intimate', 'Modern & Trendy', 'Cozy & Quiet'],
    nearby_landmarks: ['Hauz Khas Historical Lake', 'Deer Park', 'Green Park Metro'],
    heritage_area: true,
    specialty_dishes: ['Coastal Moilee with Appams', 'Avocado Tartine', 'Cold Brew Tonic'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22222222-0000-4000-8000-000000000010',
    name: 'The Big Chill Cafe',
    slug: 'the-big-chill-cafe-saket',
    short_description: 'Celebrated Italian bistro in Select Citywalk famed for Penne Vodka, decadent desserts, and retro Hollywood posters.',
    long_description: 'The Big Chill Cafe is an iconic South Delhi staple. Known for its retro movie poster walls, brick columns, hearty portions of homemade pasta, and a legendary glass counter filled with luscious cheesecakes, mudpies, and shakes.',
    cuisine_types: ['Italian', 'Cafe', 'Desserts', 'Continental', 'Beverages'],
    meal_types: ['Lunch', 'Snacks', 'Dinner'],
    price_range: '₹₹₹',
    average_cost_for_two: 1200,
    address_line1: '1st Floor, Select Citywalk Mall, Saket District Centre',
    address_line2: '',
    landmark: 'Select Citywalk 1st Floor',
    city: 'Saket, New Delhi',
    state: 'Delhi',
    pincode: '110017',
    country: 'India',
    latitude: 28.5285,
    longitude: 77.2192,
    phone: '+91 11 4111 5111',
    whatsapp_number: '+91 11 4111 5111',
    cover_image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1000&auto=format&fit=crop&q=80',
    is_open: true,
    opening_hours: {
      Monday: { open: '12:00 PM', close: '11:30 PM', is_closed: false },
      Tuesday: { open: '12:00 PM', close: '11:30 PM', is_closed: false },
      Wednesday: { open: '12:00 PM', close: '11:30 PM', is_closed: false },
      Thursday: { open: '12:00 PM', close: '11:30 PM', is_closed: false },
      Friday: { open: '12:00 PM', close: '11:30 PM', is_closed: false },
      Saturday: { open: '12:00 PM', close: '11:30 PM', is_closed: false },
      Sunday: { open: '12:00 PM', close: '11:30 PM', is_closed: false },
    },
    delivery_available: true,
    takeaway_available: true,
    dine_in_available: true,
    facilities: ['Air Conditioned', 'Mall Parking', 'Indoor Seating', 'Family Friendly', 'Dessert Counter'],
    dietary_options: ['Pure Veg', 'Vegan Options'],
    rating_avg: 4.8,
    rating_count: 8420,
    is_featured: true,
    is_active: true,
    is_temporarily_closed: false,
    known_for_dishes: ['Penne in Vodka Sauce', 'Belgian Chocolate Shake', 'Four Cheese Ravioli', 'Mississippi Mud Pie'],
    best_for_tags: ['Groups', 'Date Night', 'Coffee'],
    ambience_tags: ['Lively & Social', 'Modern & Trendy'],
    nearby_landmarks: ['Select Citywalk South Court', 'DLF Avenue Saket', 'Malviya Nagar Metro'],
    heritage_area: false,
    specialty_dishes: ['Penne in Vodka Sauce', 'Belgian Chocolate Shake', 'Mississippi Mud Pie'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22222222-0000-4000-8000-000000000011',
    name: 'The Study Table Cafe',
    slug: 'the-study-table-cafe-mukherjee-nagar',
    short_description: 'Premier aspirant-friendly study cafe with individual charging sockets, high-speed Wi-Fi, unlimited chai, and student thalis.',
    long_description: 'Designed specifically for UPSC and competitive examination aspirants in Mukherjee Nagar, The Study Table Cafe provides sound-buffered quiet zones, ergonomic seating, dedicated power outlets on every table, high-speed fiber internet, and affordable nutritious meals under ₹150.',
    cuisine_types: ['Cafe', 'North Indian', 'Chai', 'Student Thalis', 'Fast Food'],
    meal_types: ['Breakfast', 'Lunch', 'Snacks', 'Dinner', 'Late Night'],
    price_range: '₹',
    average_cost_for_two: 250,
    address_line1: 'Near Batra Cinema, Commercial Complex, Mukherjee Nagar',
    address_line2: '',
    landmark: 'Opposite Batra Cinema Complex',
    city: 'Mukherjee Nagar, New Delhi',
    state: 'Delhi',
    pincode: '110009',
    country: 'India',
    latitude: 28.7135,
    longitude: 77.2138,
    phone: '+91 98734 55112',
    whatsapp_number: '+91 98734 55112',
    cover_image_url: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=1000&auto=format&fit=crop&q=80',
    is_open: true,
    opening_hours: {
      Monday: { open: '07:00 AM', close: '01:00 AM', is_closed: false },
      Tuesday: { open: '07:00 AM', close: '01:00 AM', is_closed: false },
      Wednesday: { open: '07:00 AM', close: '01:00 AM', is_closed: false },
      Thursday: { open: '07:00 AM', close: '01:00 AM', is_closed: false },
      Friday: { open: '07:00 AM', close: '01:00 AM', is_closed: false },
      Saturday: { open: '07:00 AM', close: '01:00 AM', is_closed: false },
      Sunday: { open: '07:00 AM', close: '01:00 AM', is_closed: false },
    },
    delivery_available: true,
    takeaway_available: true,
    dine_in_available: true,
    facilities: ['Free WiFi', 'Power Outlets', 'Quiet Study Zone', 'Air Conditioned', 'Student Discount'],
    dietary_options: ['Pure Veg'],
    rating_avg: 4.7,
    rating_count: 2190,
    is_featured: true,
    is_active: true,
    is_temporarily_closed: false,
    known_for_dishes: ['Unlimited Aspirant Thali', 'Kulhad Adrak Chai', 'Paneer Grilled Sandwich', 'Cold Coffee with Ice Cream'],
    best_for_tags: ['Studying', 'Budget', 'Coffee', 'Late Night'],
    ambience_tags: ['Cozy & Quiet'],
    nearby_landmarks: ['Batra Cinema Complex', 'Vajiram Study Center', 'GTB Nagar Metro Station'],
    heritage_area: false,
    specialty_dishes: ['Unlimited Aspirant Thali', 'Kulhad Chai', 'Paneer Grilled Sandwich'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const EXTRA_ZONE_CATEGORIES: MenuCategory[] = [
  // BYD
  { id: '33333333-0000-4000-8000-000000000001', restaurant_id: '22222222-0000-4000-8000-000000000001', name: 'Student Favourites', sort_order: 1, is_active: true, created_at: new Date().toISOString() },
  { id: '33333333-0000-4000-8000-000000000002', restaurant_id: '22222222-0000-4000-8000-000000000001', name: 'Baked Pastas', sort_order: 2, is_active: true, created_at: new Date().toISOString() },
  { id: '33333333-0000-4000-8000-000000000003', restaurant_id: '22222222-0000-4000-8000-000000000001', name: 'Monster Shakes', sort_order: 3, is_active: true, created_at: new Date().toISOString() },
  // Ricos
  { id: '33333333-0000-4000-8000-000000000004', restaurant_id: '22222222-0000-4000-8000-000000000002', name: 'Artisan Pastas', sort_order: 1, is_active: true, created_at: new Date().toISOString() },
  { id: '33333333-0000-4000-8000-000000000005', restaurant_id: '22222222-0000-4000-8000-000000000002', name: 'Waffles & Bakes', sort_order: 2, is_active: true, created_at: new Date().toISOString() },
  // Tom Uncle
  { id: '33333333-0000-4000-8000-000000000006', restaurant_id: '22222222-0000-4000-8000-000000000003', name: 'Legendary Maggi Creations', sort_order: 1, is_active: true, created_at: new Date().toISOString() },
  { id: '33333333-0000-4000-8000-000000000007', restaurant_id: '22222222-0000-4000-8000-000000000003', name: 'Chai & Campus Sodas', sort_order: 2, is_active: true, created_at: new Date().toISOString() },
  // AMA
  { id: '33333333-0000-4000-8000-000000000008', restaurant_id: '22222222-0000-4000-8000-000000000004', name: 'Mountain Breakfast & Pancakes', sort_order: 1, is_active: true, created_at: new Date().toISOString() },
  { id: '33333333-0000-4000-8000-000000000009', restaurant_id: '22222222-0000-4000-8000-000000000004', name: 'Artisan Coffee Roasts', sort_order: 2, is_active: true, created_at: new Date().toISOString() },
  // United Coffee House
  { id: '33333333-0000-4000-8000-000000000010', restaurant_id: '22222222-0000-4000-8000-000000000006', name: 'Heritage Signatures Since 1942', sort_order: 1, is_active: true, created_at: new Date().toISOString() },
  // Social HKV
  { id: '33333333-0000-4000-8000-000000000011', restaurant_id: '22222222-0000-4000-8000-000000000008', name: 'Social Signatures', sort_order: 1, is_active: true, created_at: new Date().toISOString() },
  // Study Table
  { id: '33333333-0000-4000-8000-000000000012', restaurant_id: '22222222-0000-4000-8000-000000000011', name: 'Aspirant Thalis & Meals', sort_order: 1, is_active: true, created_at: new Date().toISOString() },
];

export const EXTRA_ZONE_MENU_ITEMS: MenuItem[] = [
  // BYD
  {
    id: '66666666-0000-4000-8000-000000000001',
    restaurant_id: '22222222-0000-4000-8000-000000000001',
    category_id: '33333333-0000-4000-8000-000000000001',
    name: 'BYD Cheese Bomb Burger',
    slug: 'byd-cheese-bomb-burger',
    description: 'Crispy herb patty loaded with molten cheddar cheese lava, jalapenos, and signature secret tangy dressing.',
    price: 160,
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['Veg'],
    spice_level: 2,
    portion_size: 'Regular',
    is_available: true,
    sort_order: 1,
    is_featured: true,
    is_must_try: true,
    view_count: 340,
    order_count: 190,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '66666666-0000-4000-8000-000000000002',
    restaurant_id: '22222222-0000-4000-8000-000000000001',
    category_id: '33333333-0000-4000-8000-000000000002',
    name: 'Baked Cheesy Alfredo Pasta',
    slug: 'baked-cheesy-alfredo-pasta',
    description: 'Penne pasta tossed in garlic parmesan white sauce, topped with double mozzarella, and baked golden brown.',
    price: 195,
    image_url: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281729?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['Veg'],
    spice_level: 1,
    portion_size: 'Large',
    is_available: true,
    sort_order: 2,
    is_featured: true,
    is_must_try: true,
    view_count: 480,
    order_count: 310,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '66666666-0000-4000-8000-000000000003',
    restaurant_id: '22222222-0000-4000-8000-000000000001',
    category_id: '33333333-0000-4000-8000-000000000003',
    name: 'Ferrero Rocher Monster Shake',
    slug: 'ferrero-rocher-monster-shake',
    description: 'Giant chocolate thick shake crowned with Ferrero Rocher, Nutella drizzle, whipped cream, and chocolate wafer stick.',
    price: 165,
    image_url: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['Veg'],
    spice_level: 0,
    portion_size: '500ml',
    is_available: true,
    sort_order: 3,
    is_featured: true,
    is_must_try: true,
    view_count: 290,
    order_count: 140,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Tom Uncle
  {
    id: '66666666-0000-4000-8000-000000000004',
    restaurant_id: '22222222-0000-4000-8000-000000000003',
    category_id: '33333333-0000-4000-8000-000000000006',
    name: 'Double Butter Masala Maggi',
    slug: 'double-butter-masala-maggi',
    description: 'Original 1978 campus recipe: double Maggi noodles cooked with two cubes of melted Amul butter and secret roasted masalas.',
    price: 90,
    image_url: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['Veg'],
    spice_level: 3,
    portion_size: 'Double',
    is_available: true,
    sort_order: 1,
    is_featured: true,
    is_must_try: true,
    view_count: 920,
    order_count: 670,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '66666666-0000-4000-8000-000000000005',
    restaurant_id: '22222222-0000-4000-8000-000000000003',
    category_id: '33333333-0000-4000-8000-000000000006',
    name: 'Cheese Corn Burst Maggi',
    slug: 'cheese-corn-burst-maggi',
    description: 'Hot wok-tossed Maggi loaded with sweet American corn and smothered in grated cheddar cheese.',
    price: 110,
    image_url: 'https://images.unsplash.com/photo-1594998893017-36147cbcae05?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['Veg'],
    spice_level: 2,
    portion_size: 'Double',
    is_available: true,
    sort_order: 2,
    is_featured: true,
    is_must_try: true,
    view_count: 510,
    order_count: 320,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // AMA Cafe
  {
    id: '66666666-0000-4000-8000-000000000006',
    restaurant_id: '22222222-0000-4000-8000-000000000004',
    category_id: '33333333-0000-4000-8000-000000000008',
    name: 'Fluffy Blueberry Pancakes',
    slug: 'fluffy-blueberry-pancakes',
    description: 'Three stacked golden buttermilk pancakes filled with whole blueberries, served with Canadian maple syrup and churned butter.',
    price: 240,
    image_url: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['Veg'],
    spice_level: 0,
    portion_size: 'Stack of 3',
    is_available: true,
    sort_order: 1,
    is_featured: true,
    is_must_try: true,
    view_count: 760,
    order_count: 420,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // United Coffee House
  {
    id: '66666666-0000-4000-8000-000000000007',
    restaurant_id: '22222222-0000-4000-8000-000000000006',
    category_id: '33333333-0000-4000-8000-000000000010',
    name: 'Special Cona Blend Coffee',
    slug: 'special-cona-blend-coffee',
    description: 'Iconic 1942 vacuum-brewed Cona table coffee served piping hot with milk pot and demerara sugar crystals.',
    price: 240,
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['Veg'],
    spice_level: 0,
    portion_size: 'Pot for 2',
    is_available: true,
    sort_order: 1,
    is_featured: true,
    is_must_try: true,
    view_count: 880,
    order_count: 530,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '66666666-0000-4000-8000-000000000008',
    restaurant_id: '22222222-0000-4000-8000-000000000006',
    category_id: '33333333-0000-4000-8000-000000000010',
    name: 'UCH Signature Cheese Balls',
    slug: 'uch-signature-cheese-balls',
    description: 'Golden fried crispy potato and sharp aged cheese croquettes served with home-made mustard dip and tomato chutney.',
    price: 360,
    image_url: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['Veg'],
    spice_level: 1,
    portion_size: '6 pieces',
    is_available: true,
    sort_order: 2,
    is_featured: true,
    is_must_try: true,
    view_count: 620,
    order_count: 380,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Study Table
  {
    id: '66666666-0000-4000-8000-000000000009',
    restaurant_id: '22222222-0000-4000-8000-000000000011',
    category_id: '33333333-0000-4000-8000-000000000012',
    name: 'Unlimited Aspirant Special Thali',
    slug: 'unlimited-aspirant-special-thali',
    description: 'Generous student thali: Dal Makhani, Shahi Paneer, Jeera Rice, 4 Butter Tawa Rotis, Boondi Raita, Salad & Sweet.',
    price: 140,
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['Veg'],
    spice_level: 2,
    portion_size: 'Full Thali',
    is_available: true,
    sort_order: 1,
    is_featured: true,
    is_must_try: true,
    view_count: 450,
    order_count: 310,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
